version: '3.8' # 2021.04現在

services:
  main:
    build: .
    shm_size: '2gb'
    container_name: 'BigGANomaly'
    ports:
      - '50000:8888'  # Jupyter-notebook
      - '8097:8097'
    volumes:
      - ../workspace:/workspace
    working_dir: /workspace
    command: bash -c "jupyter notebook --allow-root"
    runtime: nvidia  # ← ここを追加！
    # deploy:  # Swarm用。composeでは無視されるためコメントアウトまたは削除
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['0']
    #           capabilities: [gpu]
